### ISSUE TITLE
Add emailing support

### ISSUE THREAD

**Issue by frague59** [yeKcim/my_nautilus_scripts#1]
Add a "Send by email" for "generic" files

**Comment by yeKcim** [comment]
\o/ The first comment ! Welcome :-)

unfortunatly, this feature doesn't works well on my own computers, xdg-email doesn't take --attach argument (I'm not alone : [1](https://bugs.kde.org/show_bug.cgi?id=205572) [2](https://bugs.launchpad.net/ubuntu/+source/xdg-utils/+bug/1277884) [3](https://bugs.launchpad.net/ubuntu/+source/simple-scan/+bug/515386) [4](https://bugzilla.redhat.com/show_bug.cgi?id=820354) [5](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=491499))

**Comment by yeKcim** [comment]
https://github.com/yeKcim/my_nautilus_scripts/blob/master/mail/send%20by%20mail

done!
