### ISSUE TITLE
svg scripts - Changes with inkscape 1.0

### ISSUE THREAD

**Issue by hugotrip** [yeKcim/my_nautilus_scripts#10]
With the release of inkscape 1.0, the cli arguments have changed : for example, in the export to png scripts I had to change the line
	        inkscape -d "$resolution" -e "$output" "$input"
to 
	        inkscape -d "$resolution" --export-type=png "$input"

**Comment by yeKcim** [comment]
- [x] https://github.com/yeKcim/my_nautilus_scripts/commit/c384846b9ba806068fcccdb8cbb4d401c8a01800

Thanks a lot
