### ISSUE TITLE
clean-metadata

### ISSUE THREAD

**Issue by sla-te** [yeKcim/my_nautilus_scripts#5]
https://ghostbin.com/paste/u4en8

plz check the log 

+ qpdf --linearize /home/*/Downloads/test.pdf.clean.pdf /home/*/Downloads/test_nometa.pdf
+ pdftk /home/*/Downloads/test_nometa.pdf.pdf dump_data
Error: Unable to find file.
Error: Failed to open PDF file:

**Comment by sla-te** [comment]
Found it already :)
Line 115 it must be 		qpdf --linearize $input.clean.pdf $output**.pdf**

**Comment by yeKcim** [comment]
thanks for report.
